services:
  - type: web
    name: eduportal
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: eduportal-db-alwencasagann-f17b.a.aivencloud.com
      - key: DB_PORT
        value: "17436"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL_MODE
        value: require
      - key: SITE_URL
        value: https://reesnhs.l.cd
      - key: PLATFORM_NAME
        value: EduPortal LMS
    disk:
      name: uploads
      mountPath: /var/www/html/uploads
      sizeGB: 1

