services:
  - type: web
    name: eduportal
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: eduportal-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: eduportal-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: eduportal-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: eduportal-db
          property: database
      - key: SMTP_USER
        value: eduportal.official.pvt@gmail.com
      - key: SMTP_PASS
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SITE_URL
        value: https://reesnhs.l.cd
      - key: PLATFORM_NAME
        value: EduPortal LMS
    disk:
      name: uploads
      mountPath: /var/www/html/uploads
      sizeGB: 1

databases:
  - name: eduportal-db
    databaseName: eduportal
    user: eduportal_user
    plan: free
